version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tickette_container
    environment:
      POSTGRES_USER: HaiNguyen
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tickette-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U HaiNguyen -d tickette-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
